In [1]:
import pandas as pd
import numpy as np
#data='https://github.com/santoh15/ML-zoomcamp/blob/main/Modelo%20churn/churn.csv?plain=1'
#!wget $data


In [2]:
df=pd.read_csv('churn.csv')

In [3]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [4]:
df.columns=df.columns.str.lower().str.replace(' ','_')

In [5]:
categorical_columns=list(df.dtypes[ df.dtypes == 'object' ].index)

In [6]:
for i in categorical_columns:
    df[i]=df[i].str.lower().str.replace(' ','_')

In [7]:
df

customerid  gender  seniorcitizen partner dependents  tenure  \
0     7590-vhveg  female              0     yes         no       1   
1     5575-gnvde    male              0      no         no      34   
2     3668-qpybk    male              0      no         no       2   
3     7795-cfocw    male              0      no         no      45   
4     9237-hqitu  female              0      no         no       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-resvb    male              0     yes        yes      24   
7039  2234-xaduh  female              0     yes        yes      72   
7040  4801-jzazl  female              0     yes        yes      11   
7041  8361-ltmkd    male              1     yes         no       4   
7042  3186-ajiek    male              0      no         no      66   

     phoneservice     multiplelines internetservice onlinesecurity  ...  \
0              no  no_phone_service             dsl             no  ...   
1             yes                no             dsl            yes  ...   
2             yes                no             dsl            yes  ...   
3              no  no_phone_service             dsl            yes  ...   
4             yes                no     fiber_optic             no  ...   
...           ...               ...             ...            ...  ...   
7038          yes               yes             dsl            yes  ...   
7039          yes               yes     fiber_optic             no  ...   
7040           no  no_phone_service             dsl            yes  ...   
7041          yes               yes     fiber_optic             no  ...   
7042          yes                no     fiber_optic            yes  ...   

     deviceprotection techsupport streamingtv streamingmovies        contract  \
0                  no          no          no              no  month-to-month   
1                 yes          no          no              no        one_year   
2                  no          no          no              no  month-to-month   
3                 yes         yes          no              no        one_year   
4                  no          no          no              no  month-to-month   
...               ...         ...         ...             ...             ...   
7038              yes         yes         yes             yes        one_year   
7039              yes          no         yes             yes        one_year   
7040               no          no          no              no  month-to-month   
7041               no          no          no              no  month-to-month   
7042              yes         yes         yes             yes        two_year   

     paperlessbilling              paymentmethod monthlycharges  totalcharges  \
0                 yes           electronic_check          29.85         29.85   
1                  no               mailed_check          56.95        1889.5   
2                 yes               mailed_check          53.85        108.15   
3                  no  bank_transfer_(automatic)          42.30       1840.75   
4                 yes           electronic_check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              yes               mailed_check          84.80        1990.5   
7039              yes    credit_card_(automatic)         103.20        7362.9   
7040              yes           electronic_check          29.60        346.45   
7041              yes               mailed_check          74.40         306.6   
7042              yes  bank_transfer_(automatic)         105.65        6844.5   

     churn  
0       no  
1       no  
2      yes  
3       no  
4      yes  
...    ...  
7038    no  
7039    no  
7040    no  
7041   yes  
7042    no  

[7043 rows x 21 columns]

In [8]:
df.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges         object
churn                object
dtype: object

In [9]:
df.totalcharges=pd.to_numeric(df.totalcharges, errors='coerce')

In [10]:
df.totalcharges=df.totalcharges.fillna(0)

In [11]:
df.churn=(df.churn == 'yes').astype(int)

In [12]:
df.churn

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: churn, Length: 7043, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
df_train_full,df_test=train_test_split(df,test_size=0.2,random_state=1)

In [15]:
df_train,df_val=train_test_split(df_train_full,test_size=0.25,random_state=1)

In [16]:
len(df_train),len( df_test),len( df_val)

(4225, 1409, 1409)

In [17]:
df_train=df_train.reset_index(drop=True)
df_val=df_val.reset_index(drop=True)
df_test=df_test.reset_index(drop=True)

In [18]:
y_train=df_train.churn.values
y_val=df_val.churn.values
y_test=df_test.churn.values

In [19]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

In [20]:
y_train.mean()

np.float64(0.2686390532544379)

In [21]:
y_test.mean()

np.float64(0.24698367636621718)

In [22]:
y_val.mean()

np.float64(0.2739531582682754)

In [23]:
df_train_full.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='object')

In [24]:
numerical_variables=['tenure', 'monthlycharges', 'totalcharges']

In [25]:
categorias=['gender', 'seniorcitizen', 'partner', 'dependents',
       'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']

Vemos cuales de todas esas son binarias

In [26]:
df_train_full[categorias].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [27]:
churn_partner=df_train_full[df_train_full.partner == 'yes'].churn.mean()
churn_partner

np.float64(0.20503330866025166)

In [28]:
churn_no_partner=df_train_full[df_train_full.partner == 'no'].churn.mean()
churn_no_partner

np.float64(0.3298090040927694)

In [29]:
global_churn= df_train_full.churn.mean()

In [30]:
for c in categorias:
    df_group=df_train_full.groupby(c).churn.agg(['mean','count'])
    df_group['diff']=df_group['mean']-global_churn
    df_group['risk']=df_group['mean']/global_churn
    display(df_group)
    print()
    print()

mean  count      diff      risk
gender                                     
female  0.276824   2796  0.006856  1.025396
male    0.263214   2838 -0.006755  0.974980

mean  count      diff      risk
seniorcitizen                                     
0              0.242270   4722 -0.027698  0.897403
1              0.413377    912  0.143409  1.531208

mean  count      diff      risk
partner                                     
no       0.329809   2932  0.059841  1.221659
yes      0.205033   2702 -0.064935  0.759472

mean  count      diff      risk
dependents                                     
no          0.313760   3968  0.043792  1.162212
yes         0.165666   1666 -0.104302  0.613651

mean  count      diff      risk
phoneservice                                     
no            0.241316    547 -0.028652  0.893870
yes           0.273049   5087  0.003081  1.011412

mean  count      diff      risk
multiplelines                                        
no                0.257407   2700 -0.012561  0.953474
no_phone_service  0.241316    547 -0.028652  0.893870
yes               0.290742   2387  0.020773  1.076948

mean  count      diff      risk
internetservice                                     
dsl              0.192347   1934 -0.077621  0.712482
fiber_optic      0.425171   2479  0.155203  1.574895
no               0.077805   1221 -0.192163  0.288201

mean  count      diff      risk
onlinesecurity                                          
no                   0.420921   2801  0.150953  1.559152
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.153226   1612 -0.116742  0.567570

mean  count      diff      risk
onlinebackup                                            
no                   0.404323   2498  0.134355  1.497672
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.217232   1915 -0.052736  0.804660

mean  count      diff      risk
deviceprotection                                        
no                   0.395875   2473  0.125907  1.466379
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.230412   1940 -0.039556  0.853480

mean  count      diff      risk
techsupport                                             
no                   0.418914   2781  0.148946  1.551717
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.159926   1632 -0.110042  0.592390

mean  count      diff      risk
streamingtv                                             
no                   0.342832   2246  0.072864  1.269897
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.302723   2167  0.032755  1.121328

mean  count      diff      risk
streamingmovies                                         
no                   0.338906   2213  0.068938  1.255358
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.307273   2200  0.037305  1.138182

mean  count      diff      risk
contract                                           
month-to-month  0.431701   3104  0.161733  1.599082
one_year        0.120573   1186 -0.149395  0.446621
two_year        0.028274   1344 -0.241694  0.104730

mean  count      diff      risk
paperlessbilling                                     
no                0.172071   2313 -0.097897  0.637375
yes               0.338151   3321  0.068183  1.252560

mean  count      diff      risk
paymentmethod                                                 
bank_transfer_(automatic)  0.168171   1219 -0.101797  0.622928
credit_card_(automatic)    0.164339   1217 -0.105630  0.608733
electronic_check           0.455890   1893  0.185922  1.688682
mailed_check               0.193870   1305 -0.076098  0.718121

Hayq eu separar las variables importantes de las menos importantes, ademas de la información mutua que tienen las variables

In [31]:
from sklearn.metrics import mutual_info_score

In [32]:
mutual_info_score(df_train_full.contract, df_train_full.churn)

0.0983203874041556

In [33]:
mutual_info_score(df_train_full.partner, df_train_full.churn)

0.009967689095399745

In [34]:
def mutual_churn_score(series):
    return mutual_info_score(series, df_train_full.churn)

In [35]:
score=df_train_full[categorias].apply(mutual_churn_score)
score.sort_values()

gender              0.000117
phoneservice        0.000229
multiplelines       0.000857
seniorcitizen       0.009410
partner             0.009968
dependents          0.012346
paperlessbilling    0.017589
streamingmovies     0.031581
streamingtv         0.031853
paymentmethod       0.043210
deviceprotection    0.043453
onlinebackup        0.046923
internetservice     0.055868
techsupport         0.061032
onlinesecurity      0.063085
contract            0.098320
dtype: float64

In [36]:
df_train_full[numerical_variables].corrwith(df_train_full.churn)

tenure           -0.351885
monthlycharges    0.196805
totalcharges     -0.196353
dtype: float64

In [37]:
from sklearn.feature_extraction import DictVectorizer

In [38]:
train_dicts=df_train[numerical_variables + categorias].to_dict(orient='records')

In [39]:
dv=DictVectorizer(sparse=False)
dv.fit(train_dicts)

DictVectorizer(sparse=False)

In [40]:
dv.get_feature_names_out(train_dicts)

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'dependents=no', 'dependents=yes',
       'deviceprotection=no', 'deviceprotection=no_internet_service',
       'deviceprotection=yes', 'gender=female', 'gender=male',
       'internetservice=dsl', 'internetservice=fiber_optic',
       'internetservice=no', 'monthlycharges', 'multiplelines=no',
       'multiplelines=no_phone_service', 'multiplelines=yes',
       'onlinebackup=no', 'onlinebackup=no_internet_service',
       'onlinebackup=yes', 'onlinesecurity=no',
       'onlinesecurity=no_internet_service', 'onlinesecurity=yes',
       'paperlessbilling=no', 'paperlessbilling=yes', 'partner=no',
       'partner=yes', 'paymentmethod=bank_transfer_(automatic)',
       'paymentmethod=credit_card_(automatic)',
       'paymentmethod=electronic_check', 'paymentmethod=mailed_check',
       'phoneservice=no', 'phoneservice=yes', 'seniorcitizen',
       'streamingmovies=no', 'streamingmovies=no_internet_service',

In [41]:
X_train= dv.fit_transform(train_dicts)

In [42]:
val_dicts=df_val[numerical_variables + categorias].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(val_dicts)
X_val= dv.fit_transform(val_dicts)

In [43]:
test_dicts=df_test[numerical_variables + categorias].to_dict(orient='records')
dv=DictVectorizer(sparse=False)
dv.fit(test_dicts)
X_test= dv.fit_transform(test_dicts)

Regresión logística

In [44]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [45]:
def linear_regression(xi):
    result=0.0
    for j in range(len(w)):
        result += xi[j]*w[j]
    return result

In [46]:
def logistic_regression(xi):
    score=w0
    for j in range(len(w)):
        score += xi[j]*w[j]
    result=sigmoid(score)
    return result

In [47]:
from sklearn.linear_model import LogisticRegression

In [51]:
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [55]:
model.intercept_[0]

np.float64(-0.045323382519725265)

In [54]:
model.coef_[0].round(3)

array([ 0.685,  0.039, -0.682,  0.056, -0.015,  0.114, -0.16 ,  0.087,
        0.039,  0.002, -0.497,  0.698, -0.16 , -0.018, -0.187,  0.066,
        0.162,  0.117, -0.16 ,  0.084,  0.285, -0.16 , -0.084, -0.161,
        0.202, -0.045,  0.086, -0.052, -0.003,  0.106, -0.011,  0.066,
       -0.025,  0.194, -0.094, -0.16 ,  0.295, -0.054, -0.16 ,  0.255,
        0.235, -0.16 , -0.034, -0.069,  0.   ])

In [56]:
model.predict(X_train)

array([0, 1, 1, ..., 1, 0, 1], shape=(4225,))

In [59]:
y_pred= model.predict_proba(X_val)[:,1] 

In [61]:
churn_decision= (y_pred >= 0.5)

In [64]:
df_val[churn_decision].customerid

3       8433-wxgna
8       3440-jpscl
12      7228-omtpn
19      6711-fldfb
24      2612-ranwt
           ...    
1397    5976-jcjrh
1398    2034-cgrhz
1399    5276-kqwhg
1407    6521-yytyi
1408    3049-solay
Name: customerid, Length: 315, dtype: object

In [65]:
churn_decision.astype(int)

array([0, 0, 0, ..., 0, 1, 1], shape=(1409,))

In [67]:
(y_val == churn_decision).mean()

np.float64(0.8034066713981547)

In [68]:
df_pred=pd.DataFrame()
df_pred['probability']=y_pred
df_pred['prediction']=churn_decision.astype(int)
df_pred['actual']=y_val

In [70]:
df_pred['correct']=df_pred.prediction==df_pred.actual

In [75]:
int((df_pred.correct== False).sum())

277

In [77]:
list(zip(dv.get_feature_names_out(), model.coef_[0].round(3)))

[('contract=month-to-month', np.float64(0.685)),
 ('contract=one_year', np.float64(0.039)),
 ('contract=two_year', np.float64(-0.682)),
 ('dependents=no', np.float64(0.056)),
 ('dependents=yes', np.float64(-0.015)),
 ('deviceprotection=no', np.float64(0.114)),
 ('deviceprotection=no_internet_service', np.float64(-0.16)),
 ('deviceprotection=yes', np.float64(0.087)),
 ('gender=female', np.float64(0.039)),
 ('gender=male', np.float64(0.002)),
 ('internetservice=dsl', np.float64(-0.497)),
 ('internetservice=fiber_optic', np.float64(0.698)),
 ('internetservice=no', np.float64(-0.16)),
 ('monthlycharges', np.float64(-0.018)),
 ('multiplelines=no', np.float64(-0.187)),
 ('multiplelines=no_phone_service', np.float64(0.066)),
 ('multiplelines=yes', np.float64(0.162)),
 ('onlinebackup=no', np.float64(0.117)),
 ('onlinebackup=no_internet_service', np.float64(-0.16)),
 ('onlinebackup=yes', np.float64(0.084)),
 ('onlinesecurity=no', np.float64(0.285)),
 ('onlinesecurity=no_internet_service', np.fl

In [78]:
dicts_full_train = df_train_full[categorias+numerical_variables].to_dict(orient='records')

In [79]:
dv=DictVectorizer(sparse=False)
X_full_train=dv.fit_transform(dicts_full_train)

In [80]:
y_full_train= df_train_full.churn.values

In [82]:
model=LogisticRegression(max_iter=10000).fit(X_full_train, y_full_train)

In [83]:
dicts_test = df_test[categorias+numerical_variables].to_dict(orient='records')

In [84]:
X_test=dv.fit_transform(dicts_test)

In [88]:
y_pred=model.predict_proba(X_test)[:,1]

In [90]:
(y_pred >= 0.5).astype(int)

array([0, 0, 0, ..., 0, 0, 1], shape=(1409,))

In [92]:
((y_pred >= 0.5).astype(int)==y_test).astype(int).mean()

np.float64(0.8105039034776437)